# Copyright © 2022 Gitleaks LLC - All Rights Reserved.
# You may use this code under the terms of the GITLEAKS-ACTION END-USER LICENSE AGREEMENT.
# You should have received a copy of the GITLEAKS-ACTION END-USER LICENSE AGREEMENT with this file.
# If not, please visit https://gitleaks.io/COMMERCIAL-LICENSE.txt

name: Gitleaks Scanner
description: Run gitleaks to detect secrets in your repositories
author: MMS

inputs:
  config-path:
    description: Path to gitleaks config file
    required: false
    default: .gitleaks.toml
  fail-on-findings:
    description: Fail the build if leaks are found
    required: false
    default: "true"

runs:
  using: "node24"
  main: "dist/index.js"
